### PR TITLE
fix small typo

### PR DESCRIPTION
**Pull request by rpivo**
Unfortunately when I save these notebooks in my IDE, it appears to update the format of some `application/javascript` segments. I'm guessing this is harmless, but I'm not sure. Feel free to close this in favor of your own edits, just wanted to surface the typo.

### CODE REVIEW

**Comment by AllenDowney** [comment]
Hmm. Not sure what's going on with the formatting.

But I'm happy to fix a typo -- can you tell me what it is? The diffs on the notebooks are big.

**Comment by rpivo** [comment]
@AllenDowney I had to disable my linter, sorry about that. The diff looks good now.

**Comment by AllenDowney** [comment]
Fixed. Thanks!

BTW, the notebooks in `soln` are the source docs, everything else gets generated automatically. So no need to change all three files. For typos, it's probably easier to open an issue rather than a PR.

**Comment by rpivo** [comment]
Ah, got it, I wasn't sure what the different files did. I will open an issue if I see something in the future. Thanks

**Pull request closed without merging**
